package com.residenciasegura.vista;

import com.residenciasegura.modelo.Usuario;
import javax.swing.JOptionPane;

/**
 * Dashboard para usuarios con rol de Guardia
 * 
 * @author DARIX
 */
public class DashboardGuardia extends javax.swing.JFrame {
    
    private final Usuario usuario;
    
    /**
     * Creates new form DashboardGuardia
     */
    public DashboardGuardia(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        configurarVentana();
    }
    
    private void configurarVentana() {
        setTitle("Residencia Segura - Panel del Guardia");
        setLocationRelativeTo(null);
        lblBienvenida.setText("Bienvenido, " + usuario.getNombre());
        lblRol.setText("Rol: Guardia");
        lblDepartamento.setText("Departamento: " + usuario.getDepartamento());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        btnVerReportes = new javax.swing.JButton();
        btnAtenderReporte = new javax.swing.JButton();
        btnVerAvisos = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));

        lblBienvenida.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblBienvenida.setText("Bienvenido");

        lblRol.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblRol.setText("Rol:");

        lblDepartamento.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDepartamento.setText("Departamento:");

        btnVerReportes.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnVerReportes.setText("Ver Reportes");
        btnVerReportes.addActionListener(this::btnVerReportesActionPerformed);

        btnAtenderReporte.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnAtenderReporte.setText("Atender Reporte");
        btnAtenderReporte.addActionListener(this::btnAtenderReporteActionPerformed);

        btnVerAvisos.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnVerAvisos.setText("Ver Avisos");
        btnVerAvisos.addActionListener(this::btnVerAvisosActionPerformed);

        btnCerrarSesion.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBienvenida)
                    .addComponent(lblRol)
                    .addComponent(lblDepartamento)
                    .addComponent(btnVerReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtenderReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblBienvenida)
                .addGap(10, 10, 10)
                .addComponent(lblRol)
                .addGap(5, 5, 5)
                .addComponent(lblDepartamento)
                .addGap(30, 30, 30)
                .addComponent(btnVerReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnAtenderReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnVerAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReportesActionPerformed
        VentanaGestionReportesGuardia ventana = new VentanaGestionReportesGuardia(usuario);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnVerReportesActionPerformed

    private void btnAtenderReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderReporteActionPerformed
        VentanaGestionReportesGuardia ventana = new VentanaGestionReportesGuardia(usuario);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnAtenderReporteActionPerformed

    private void btnVerAvisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAvisosActionPerformed
        VentanaVerAvisos ventana = new VentanaVerAvisos(usuario);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnVerAvisosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        new VentanaLogin().setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtenderReporte;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnVerAvisos;
    private javax.swing.JButton btnVerReportes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblRol;
    // End of variables declaration//GEN-END:variables
}

