package com.residenciasegura.vista;

import com.residenciasegura.modelo.Usuario;
import javax.swing.JOptionPane;

/**
 * Dashboard para usuarios con rol de Administrador
 * 
 * @author DARIX
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    private final Usuario usuario;
    
    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        configurarVentana();
    }
    
    private void configurarVentana() {
        setTitle("Residencia Segura - Panel de Administración");
        setLocationRelativeTo(null);
        lblBienvenida.setText("Bienvenido, " + usuario.getNombre());
        lblRol.setText("Rol: Administrador");
        lblDepartamento.setText("Departamento: " + usuario.getDepartamento());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        btnGestionUsuarios = new javax.swing.JButton();
        btnGestionPagos = new javax.swing.JButton();
        btnGestionReportes = new javax.swing.JButton();
        btnGestionAvisos = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblBienvenida.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblBienvenida.setText("Bienvenido");

        lblRol.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblRol.setText("Rol:");

        lblDepartamento.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDepartamento.setText("Departamento:");

        btnGestionUsuarios.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnGestionUsuarios.setText("Gestión de Usuarios");
        btnGestionUsuarios.addActionListener(this::btnGestionUsuariosActionPerformed);

        btnGestionPagos.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnGestionPagos.setText("Gestión de Pagos");
        btnGestionPagos.addActionListener(this::btnGestionPagosActionPerformed);

        btnGestionReportes.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnGestionReportes.setText("Gestión de Reportes");
        btnGestionReportes.addActionListener(this::btnGestionReportesActionPerformed);

        btnGestionAvisos.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnGestionAvisos.setText("Gestión de Avisos");
        btnGestionAvisos.addActionListener(this::btnGestionAvisosActionPerformed);

        btnCerrarSesion.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(this::btnCerrarSesionActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBienvenida)
                    .addComponent(lblRol)
                    .addComponent(lblDepartamento)
                    .addComponent(btnGestionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblBienvenida)
                .addGap(10, 10, 10)
                .addComponent(lblRol)
                .addGap(5, 5, 5)
                .addComponent(lblDepartamento)
                .addGap(30, 30, 30)
                .addComponent(btnGestionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnGestionPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnGestionReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnGestionAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionUsuariosActionPerformed
        VentanaGestionUsuarios ventana = new VentanaGestionUsuarios(usuario);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGestionUsuariosActionPerformed

    private void btnGestionPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPagosActionPerformed
        VentanaGestionPagos ventana = new VentanaGestionPagos(usuario);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGestionPagosActionPerformed

    private void btnGestionReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionReportesActionPerformed
        VentanaGestionReportes ventana = new VentanaGestionReportes(usuario);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGestionReportesActionPerformed

    private void btnGestionAvisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionAvisosActionPerformed
        VentanaGestionAvisos ventana = new VentanaGestionAvisos(usuario);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnGestionAvisosActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro que desea cerrar sesión?", 
            "Cerrar Sesión", 
            JOptionPane.YES_NO_OPTION);
        
        if (respuesta == JOptionPane.YES_OPTION) {
            this.dispose();
            new VentanaLogin().setVisible(true);
        }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionAvisos;
    private javax.swing.JButton btnGestionPagos;
    private javax.swing.JButton btnGestionReportes;
    private javax.swing.JButton btnGestionUsuarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblRol;
    // End of variables declaration//GEN-END:variables
}

